### DISCUSSION TITLE
关于用例中multipart/form-data上传图片的问题

### DISCUSSION THREAD

**Discussion by Tsn-09** [httprunner/httprunner#1516] [2 - 答疑（Q&A）]
如何构建这样格式的body？
```
------WebKitFormBoundary1FXI0ceMIWIKPx60
Content-Disposition: form-data; name="width"

200
------WebKitFormBoundary1FXI0ceMIWIKPx60
Content-Disposition: form-data; name="height"

200
------WebKitFormBoundary1FXI0ceMIWIKPx60
Content-Disposition: form-data; name="file"; filename="event_type.png"
Content-Type: image/png


------WebKitFormBoundary1FXI0ceMIWIKPx60--
```
尝试按照下面这种用例格式，没有成功
```
name: 图片上传
  variables:
    file_path: /root/testcase/1.jpeg
    m_encoder: ${multipart_encoder(file=${file_path})}
  request:
    method: POST
    url: /uploadImg
    headers:
      Content-Type: ${multipart_content_type(${m_encoder})}
    upload:
      file: $file_path
      width: 200
      height: 200

```
结果是这样的：
```
--272318aad776f6b6b222dc1a991ba8afda4b6c6c77458810ea25c3cedbaf
Content-Disposition: form-data; name="width"

200
--272318aad776f6b6b222dc1a991ba8afda4b6c6c77458810ea25c3cedbaf
Content-Disposition: form-data; name="height"

200
--272318aad776f6b6b222dc1a991ba8afda4b6c6c77458810ea25c3cedbaf
Content-Disposition: form-data; name="file"

(/root/testcase/1.jpeg)
--272318aad776f6b6b222dc1a991ba8afda4b6c6c77458810ea25c3cedbaf--
```

原因在于 file 这个关键字，也被当成普通字段处理了，而不是文件。
所以请教一下大家，该如何处理

hrp version v4.2.0
