### ISSUE TITLE
${sum_two(${x}, ${a})} 执行报错

### ISSUE THREAD

**Issue by whitexie** [httprunner/httprunner#1009]
## 问题描述

请对遇到的 bug 进行简要描述。

## 版本信息

请提供如下版本信息：

 - 操作系统类型：Linux
 - Python 版本：3.7
 - HttpRunner 版本：3.1.4
 - **设备 ID**：95529610562

## 项目文件内容（非必须）
```yml
config:
    name: run with httprunner
    base_url: https://httpbin.org/

teststeps:
-
    name: headers
    request:
        url: /headers
        method: GET
        headers:
            d: "123"
            f: "321"
    validate:
        - eq: ["status_code", 200]
    extract:
        x: content.headers.D
        a: content.headers.F

-
    name: user-agent
    request:
        url: /get
        method: GET
        params:
            age: ${x}
            team: $team_v
            name: Testerhom
    variables:
        team_v: "${sum_two(${x}, ${a})}"
    validate:
        - eq: ["status_code", 200]
        - eq: ["content.args.team", 3]
    extract:
        foo1: content.args.name
```

## 运行命令 && 堆栈信息

请提供在命令行中运行测试时所在的目录和命令，以及报错时的详细堆栈内容。

```bash
2020-09-14 17:22:54.890 | ERROR    | httprunner.response:validate:263 - assert body.args.team equal 123321(str) ==> fail
check_item: body.args.team
check_value: ${sum_two(123,321)}(str)
assert_method: equal
expect_value: 123321(str)

```
