### ISSUE TITLE
yml 用例中调用 yml文件

### ISSUE THREAD

**Issue by Deacone** [httprunner/httprunner#1023]
## 问题描述
在yml文件的用例中调用 另一个yml文件的测试用例报错：TestCaseFormatError

运行如下用例，报错：TestCaseFormatError
用例：
```yml
config:
    name: "request methods testcase: reference testcase"
    variables:
        foo1: testsuite_config_bar1
        expect_foo1: testsuite_config_bar1
        expect_foo2: config_bar2
    base_url: "https://postman-echo.com"
    verify: False

teststeps:
-
    name: request with functions
    variables:
        foo1: testcase_ref_bar1
        expect_foo1: testcase_ref_bar1
    setup_hooks:
        - ${sleep(0.1)}
    testcase: request_methods/request_with_functions.yml
    teardown_hooks:
        - ${sleep(0.2)}
    export:
        - foo3
-
    name: post form data
    variables:
        foo1: bar1
    request:
        method: POST
        url: /post
        headers:
            User-Agent: HttpRunner/${get_httprunner_version()}
            Content-Type: "application/x-www-form-urlencoded"
        data: "foo1=$foo1&foo2=$foo3"
    validate:
        - eq: ["status_code", 200]
        - eq: ["body.form.foo1", "bar1"]
        - eq: ["body.form.foo2", "bar21"]

```

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [macos]
 - Python 版本 [3.7]
 - HttpRunner 版本 [3.1.4]

获取方式：
直接运行单元测试文件：tests/make_test.py::test_make_testcase_with_ref

## 项目文件内容（非必须）

如果可能，提供项目测试用例文件原始内容可加快 bug 定位和修复速度。

提示：请注意在去除项目敏感信息（IP、账号密码、密钥等）后再进行上传。

## 运行命令 && 堆栈信息

请提供在命令行中运行测试时所在的目录和命令，以及报错时的详细堆栈内容。

## 报错信息
```
httprunner.make:__make:588 - Invalid test_cases file: /Users/donghp/Downloads/Git_doc/PythonProject/httprunner/examples/postman_echo/request_methods/request_with_testcase_reference.yml
TestCaseFormatError: Invalid teststep: {'name': 'request with functions', 'variables': {'foo1': 'testcase_ref_bar1', 'expect_foo1': 'testcase_ref_bar1'}, 'testcase': 'request_methods/request_with_functions.yml', 'setup_hooks': ['${sleep(0.1)}'], 'teardown_hooks': ['${sleep(0.2)}'], 'export': ['foo3']}
```
