### ISSUE TITLE
测试套件下的测试用例不一定按顺序执行

### ISSUE THREAD

**Issue by vankillua** [httprunner/httprunner#1070]
## 问题描述

请对遇到的 bug 进行简要描述。

## 版本信息

请提供如下版本信息：

 - 操作系统类型: macos
 - Python 版本 3.6
 - HttpRunner 版本 3.1.4

获取方式：

`httprunner/make.py`源码分析如下：

**pytest_files_run_set是一个无序的不重复的集合，往里面添加pytest文件后的顺序不一定跟添加的顺序一致，最终pytest执行的用例列表中的顺序就有可能错误**

![image](https://user-images.githubusercontent.com/20939027/108810129-62c57380-75e5-11eb-8085-1d412f0c8a1a.png)
![image](https://user-images.githubusercontent.com/20939027/108810170-7ec91500-75e5-11eb-9ff0-3e2621901f02.png)
![image](https://user-images.githubusercontent.com/20939027/108810254-b1730d80-75e5-11eb-88a2-bf5134b830e7.png)
![image](https://user-images.githubusercontent.com/20939027/108810454-20e8fd00-75e6-11eb-8a6f-5d2382c6bea1.png)

**出现此问题时的情况，如下图：**
![image](https://user-images.githubusercontent.com/20939027/108809554-162d6880-75e4-11eb-911e-85f55226fda9.png)

## 项目文件内容（非必须）

- `testsuite.yml`内容如下：
```yaml
config:
  name: 测试集样例
  base_url: https://httpbin.org
  verify: false
  # testsuite config variables
  variables:
    varA: suiteConfigVarA
    varB: suiteConfigVarB
    varC: suiteConfigVarC

testcases:
  - name: 测试集样例 - 测试用例1
    # testcase variables
    variables:
      varA: case1VarA
      varB: case1VarB
    testcase: testsuite/testcase1.yml
  - name: 测试集样例 - 测试用例2
    # testcase variables
    variables:
      varA: case2VarA
    testcase: testsuite/testcase2.yml
  - name: 测试集样例 - 测试用例3
    # testcase variables
    variables:
      varA: case3VarA
    testcase: testsuite/testcase3.yml
```

- `testcase1.yml`内容如下：
```yaml
config:
  name: 测试用例1
  # referenced testcase config variables
  variables:
    varA: case1ConfigVarA
    varB: case1ConfigVarB
    varC: case1ConfigVarC
    varD: case1ConfigVarD

teststeps:
  - name: 测试用例1 - 步骤1
    variables:
      varA: case1Step1VarA
    request:
      method: GET
      url: /get
      params:
        varA: $varA
        varB: $varB
        varC: $varC
        varD: $varD
    # referenced testcase step variables > testcase variables > testsuite config variables > referenced testcase config variables
    validate:
      - eq: [ "status_code", 200 ]
      - eq: [ "body.args.varA", "case1Step1VarA" ]
      - eq: [ "body.args.varB", "case1VarB" ]
      - eq: [ "body.args.varC", "suiteConfigVarC" ]
      - eq: [ "body.args.varD", "case1ConfigVarD" ]
```

- `testcase2.yml`内容如下：
```yaml
config:
  name: 测试用例2
  variables:
    varA: case2ConfigVarA
    varB: case2ConfigVarB

teststeps:
  - name: 测试用例2 - 步骤1
    request:
      method: GET
      url: /get
      params:
        varA: $varA
        varB: $varB
    # 通过teardown钩子修改response中的值（模拟服务端返回了其它的值）
    teardown_hooks:
      - ${teardown_hook_step2($response)}
    # extract variables
    extract:
      varA: "body.args.varA"
      varB: "body.args.varB"
    validate:
      - eq: [ "status_code", 200 ]
      - eq: [ "body.args.varA", "step2ExtractVarA" ]
      - eq: [ "body.args.varB", "step2ExtractVarB" ]
```

- `testcase3.yml`内容如下：
```yml
config:
  name: 测试用例3
  variables:
    varA: case3ConfigVarA
    varB: case3ConfigVarB

teststeps:
  - name: 测试用例3 - 步骤1
    request:
      method: GET
      url: /get
      params:
        varA: $varA
        varB: $varB
    validate:
      - eq: [ "status_code", 200 ]
      - eq: [ "body.args.varA", "step2ExtractVarA" ]
      - eq: [ "body.args.varB", "step2ExtractVarB" ]
```
