### ISSUE TITLE
response中的headers无法获取

### ISSUE THREAD

**Issue by wushuangcangye** [httprunner/httprunner#1071]
## Describe the bug
    登录后的cookie存在response headers中，断言时还能获取到reponse headers，但是使用extract和teardown_hocks时，response中只有body内容,headers字段也不能识别
   希望能在extract和teardown_hocks中提供 response headers值的获取

## Versions
 - OS: [macos]
 - Python [e.g. 3.8]
 - HttpRunner [e.g. 3.1.4]

**Comment by whitexie** [comment]
extract可以拿到headers的
```yaml
config:
    name: run with httprunner
    base_url: https://httpbin.org/

teststeps:
-
    name: headers
    request:
        url: /headers
        method: GET
    extract:
        header: "headers.Date"
    validate:
        - eq: ["status_code", 200]
```
