### ISSUE TITLE
请问httprunner里怎么设置请求的timeout呢

### ISSUE THREAD

**Issue by ayakamiki** [httprunner/httprunner#1078]
## 背景描述

> 重点描述遇到的问题：在什么场景下，HttpRunner 当前的功能特性不能（很好地）实现需求。
比如直接用requests发请求可以这么写：requests.get('http://www.baidu.com',timeout=1),那在httprunner里该怎么设置对应的timeout呢？
## 期望的功能特性

> 期望 HttpRunner 实现怎样的功能特性。

## 示例描述（可选）

> 结合示例进行描述，可让开发者更准确理解你的需求。

**Comment by whitexie** [comment]
直接在request下添加timeout就行
```yaml
config:
    name: run with httprunner_1
    base_url: https://httpbin.org/

teststeps:
-
    name: headers
    request:
        url: /headers
        method: GET
        timeout: 1
        headers:
            d: "123"
            f: "321"
    validate:
        - eq: ["status_code", 200]
    extract:
        x: content.headers.D
        a: content.headers.F

```
