### ISSUE TITLE
执行接口定义（API）的yml文件时，报base_url不存在

### ISSUE THREAD

**Issue by zhangboyi** [httprunner/httprunner#1092]
## 问题描述

请对遇到的 bug 进行简要描述。

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [macos]
 - Python 版本 [3.8]
 - HttpRunner 版本： 3.1.5
 ## 使用的案例
![image](https://user-images.githubusercontent.com/40347463/124357537-9c228580-dc4e-11eb-9030-a5f00401616b.png)

## 接口定义的yaml文件
```yml

name: get headers
base_url: http://httpbin.org
variables:
    expected_status_code: 200
request:
    url: /headers
    method: GET
validate:
    - eq: ["status_code", $expected_status_code]
    - eq: [content.headers.Host, "httpbin.org"]
```
执行`hrun api/get_headers.yml`，报错：提示base_url is miss。
生成对应的test文件：get_headers_test.py

```python
from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseGetHeaders(HttpRunner):
   # 缺少该选项  .base_url("http://httpbin.org")
    config = Config("get headers")


    teststeps = [
        Step(
            RunRequest("get headers")
            .with_variables(**{"expected_status_code": 200})
            .get("/headers")
            .validate()
            .assert_equal("status_code", "$expected_status_code")
            .assert_equal("body.headers.Host", "httpbin.org")
        ),
    ]


if __name__ == "__main__":
    TestCaseGetHeaders().test_start()

```
## 经排查，
![image](https://user-images.githubusercontent.com/40347463/124357503-5d8ccb00-dc4e-11eb-8863-026e8f2f5549.png)
没有将base_url加入config中，导致在执行api的yml的时候，无法找到
