### ISSUE TITLE
3.1.6版本参数化所有用例都取第一个值

### ISSUE THREAD

**Issue by binbinu** [httprunner/httprunner#1140]
## 问题描述

参数化运行的所有用例都取test1值

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [macos]
 - Python 版本 [3.6]
 - HttpRunner 版本 [3.1.6]
 - **设备 ID**: [e.g. 190070690681122]

## 项目文件内容（非必须）

> 

> `

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))

from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.admin.login.login_test import TestCaseLogin as Login

class TestCaseQuerydoctorinfo(HttpRunner):

    config = Config("查询医生信息").variables(**{"user": 123}).base_url("${ENV(HOST)}")

    teststeps = [
        Step(RunTestCase("get_token").call(Login).export(*["token"])),
        Step(
            RunRequest("查询医生信息")
            .post("/jeecg/doctor/queryDoctorInfo")
            .with_headers(**{"X-Access-Token": "$token"})
            .with_json({"searchValue": "$user"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 200)
            .assert_equal("body.message", "操作成功！")
        ),
    ]

if __name__ == "__main__":
    TestCaseQuerydoctorinfo().test_start()
`

`

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))

import pytest
from httprunner import Parameters

from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.admin.医生端管理.queryDoctorInfo_test import (
    TestCaseQuerydoctorinfo as Querydoctorinfo,
)

class TestCaseQuerydoctorinfoSuites(HttpRunner):
    @pytest.mark.parametrize(
        "param", Parameters({"user": ["test1", "test2", "test3", "test4"]})
    )
    def test_start(self, param):
        super().test_start(param)

    config = Config("查询医生信息")

    teststeps = [
        Step(RunTestCase("查询医生信息").call(Querydoctorinfo)),
    ]

if __name__ == "__main__":
    TestCaseQuerydoctorinfoSuites().test_start()
`

**Comment by zhengtong0898** [comment]
@qiaomui , 你好
issue描述的代码存在排版错乱的情况, 麻烦你重新编辑并对代码重新排版.
请提供的你的日志信息, 你有两种收集日志的方式, 请选择任一一种即可:
1. 将logs目录打包, 以附件形式提交上来.
2. 将控制台的日志输出完整的赋值到一个文本文件中, 以附件形式提交上来.

**Comment by zhengtong0898** [comment]
你在yml文件里面要使用参数化的变量, 参数化才能生效.

login.yml
```yaml


config:
    name: "module variable"
    desc: "这里定义的是当前API要求必填的参数"
    variables:
        host: ""
        username: ""
        password: ""
        status_code: ""
        body_status: ""
        body_msg: ""


teststeps:
-
    name: login
    request:
        method: POST
        url: "${host}/login"
        headers:
            User-Agent: HttpRunner/${get_httprunner_version()}
            Content-Type: "application/x-www-form-urlencoded"
        data: "username=${username}&password=${password}"
    validate:
        - eq: ["status_code", "${status_code}"]
        - eq: ["body.status", "${body_status}"]
        - eq: ["body.msg", "${body_msg}"]

```

&nbsp;  
example-ref.yml
```yaml


config:
    name: "login parameters cartesian v3"
    variables:
        host: "http://127.0.0.1:8888"
        status_code: 200
    parameters:
        username: ["zhangsan", "lisi", "xiaoming"]
        password: ["zhangsan123", "lisi123", "xiaoming123"]


teststeps:
-
    name: "login"
    testcase: apis/login.yml
    variables:
        host: "http://127.0.0.1:8888"
        username: "${username}"                             # 重点在这里，你需要使用变量
        password: "${password}"                              # 重点在这里，你需要使用变量
        status_code: 200
        body_status: 200
        body_msg: "login success"

-
    name: "create user"
    request:
        method: POST
        url: "${host}/user"
        headers:
            User-Agent: HttpRunner/${get_httprunner_version()}
            Content-Type: "application/x-www-form-urlencoded"
        data: "username=${username}"
    validate:
        - eq: ["status_code", 200]
        - eq: ["body.status", 200]
        - eq: ["body.msg", "user ${username} create success."]

```

执行的日志文件:
[logs.zip](https://github.com/httprunner/httprunner/files/7825029/logs.zip)
