### ISSUE TITLE
参数化所有用例都取第一个值

### ISSUE THREAD

**Issue by binbinu** [httprunner/httprunner#1141]
## 问题描述

请对遇到的 bug 进行简要描述。

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [e.g. macos]
 - Python 版本 [e.g. 3.6]
 - HttpRunner 版本 [e.g. 3.1.6]
 - **设备 ID**: [e.g. 190070690681122]

## 项目文件内容（非必须）

```
config:
  name: login
  base_url: ${ENV(HOST)}
  variables:
    username: '${ENV(ADMIN_USER)}'
    password: '${ENV(PASSWORD)}'
  export:
    - token

teststeps:
  - name: login
    request:
      method: POST
      url: /login
      json: { 'username': '${username}', 'password': '${password}'}
    extract:
      token: "body.data.token"
    validate:
      - eq: [ "body.code", '300' ]
```

```
config:
  name: login
  parameters:
    username: [ "zhangsan", "lisi", "xiaoming" ]
    password: [ "zhangsan123", "lisi123", "xiaoming123" ]

teststeps:
  - name: "login"
    testcase: testcases/admin/login/login.yaml
    variables:
      username: '${username}'
      password: '${password}'



```
## 运行命令 && 堆栈信息

请提供在命令行中运行测试时所在的目录和命令，以及报错时的详细堆栈内容。

```bash
hrun testsuites/admin/login/login.yaml --html=./reports/report.html
```
  ## 日志文件
[logs.zip](https://github.com/httprunner/httprunner/files/7825888/logs.zip)

**Comment by zhengtong0898** [comment]
麻烦提供生成的.py文件，以及运行 httprunner 的截图.
截图信息里面至少要包含 httprunner 的版本号，以及 pytest的版本号。
![图片](https://user-images.githubusercontent.com/17564324/148486881-3fe33593-5429-4b55-b6bb-4cfd66cf5652.png)

**Comment by zhengtong0898** [comment]
根据问题中提供的yaml代码稍作调整，在我的环境下参数化是正常的。   

&nbsp;  
login-online.yml
```yaml
config:
  name: login
  base_url: "http://127.0.0.1:8888"
  variables:
    username: '${ENV(ADMIN_USER)}'
    password: '${ENV(PASSWORD)}'
  export:
    - token

teststeps:
  - name: login
    request:
      method: POST
      url: /login
      json: { 'username': '${username}', 'password': '${password}'}
    extract:
      token: "body.data.token"
    validate:
      - eq: [ "body.code", '300' ]

```

&nbsp;  
login-online-ref.yml
```yaml
config:
  name: login
  parameters:
    username: [ "zhangsan", "lisi", "xiaoming" ]
    password: [ "zhangsan123", "lisi123", "xiaoming123" ]

teststeps:
  - name: "login"
    testcase: apis/login-online.yml
    variables:
      username: '${username}'
      password: '${password}'

```


&nbsp;  
对应生成的.py文件
login_online_test.py
```python3
# NOTE: Generated By HttpRunner v3.1.6
# FROM: apis/login-online.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLoginOnline(HttpRunner):

    config = (
        Config("login")
        .variables(**{"username": "${ENV(ADMIN_USER)}", "password": "${ENV(PASSWORD)}"})
        .base_url("http://127.0.0.1:8888")
        .export(*["token"])
    )

    teststeps = [
        Step(
            RunRequest("login")
            .post("/login")
            .with_json({"username": "${username}", "password": "${password}"})
            .extract()
            .with_jmespath("body.data.token", "token")
            .validate()
            .assert_equal("body.code", "300")
        ),
    ]


if __name__ == "__main__":
    TestCaseLoginOnline().test_start()

```

&nbsp;  
login_online_ref_test.py
```python3
# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/login-online-ref.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from apis.login_online_test import TestCaseLoginOnline as LoginOnline


class TestCaseLoginOnlineRef(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "username": ["zhangsan", "lisi", "xiaoming"],
                "password": ["zhangsan123", "lisi123", "xiaoming123"],
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = Config("login")

    teststeps = [
        Step(
            RunTestCase("login")
            .with_variables(**{"username": "${username}", "password": "${password}"})
            .call(LoginOnline)
            .export(*["token"])
        ),
    ]


if __name__ == "__main__":
    TestCaseLoginOnlineRef().test_start()

```
