### ISSUE TITLE
extract提取使用[-1]无法提取到最后一位

### ISSUE THREAD

**Issue by binbinu** [httprunner/httprunner#1156]
## 问题描述

extract提取使用[-1]无法提取到最后一位, 最后一位是有值,但提取出来是none,使用[0]可以取到第一位的值

**Comment by zhengtong0898** [comment]
请尽可能的提供复现步骤

**Comment by qiaomui** [comment]
> 请提供操作代码或yaml文件, 以便我可以复现问题.
yaml文件用例
```
config:
    name: 获取商品组合
    variables: {}
    verify: false
    base_url: '${ENV(HOST)}'
    export: [token, id]
teststeps:
-   name: get_token
    testcase: testcases/admin/login/login.yaml

-   name: /jeecg/itemGroup/itemGroupList
    request:
        headers:
            Version: ${ENV(VERSION)}
            X-Access-Token: ${token}
            appid: ${ENV(APPID)}
        method: GET
        params:
            current: '1'
            searchValue: ''
            size: '10'
        url: /jeecg/itemGroup/itemGroupList
    extract:
        id: body.result.records[-1].id
    validate:
    -   eq:
        - status_code
        - 200
    -   eq:
        - body.success
        - true
    -   eq:
        - body.message
        - 操作成功！
    -   eq:
        - body.code
        - 200

```

返回数据
```
body     : {
    "success": true,
    "message": "操作成功！",
    "code": 200,
    "result": {
        "records": [
            {
                "createtime": "2022-01-10 18:15:49",
                "mainimg": "",
                "name": "大礼包",
                "count": 3,
                "spu": "",
                "id": "",
                "updatetime": "2022-01-10 18:15:48",
                "status": 1
            },
            {
                "createtime": "2022-02-10 15:44:55",
                "mainimg": "",
                "name": "测试组合",
                "count": 2,
                "spu": "",
                "id": "",
                "updatetime": "2022-02-10 15:44:55",
                "status": 1
            },]

```

日志关键信息
```
2022-02-10 16:31:33.709 | INFO     | httprunner.response:extract:179 - extract mapping: {'id': None}
```
