### ISSUE TITLE
需求: 对齐pytest的fixture作为函数参数 

### ISSUE THREAD

**Issue by zhengtong0898** [httprunner/httprunner#1160]
## 背景描述

pytest 提供了 fixture 的特性,    
并且允许在测试用例的入口函数处声明使用该fixture作为参数,   
这是一个高价值特性, 需要被支持, [pytest-fixture](https://docs.pytest.org/en/6.2.x/fixture.html)

## 期望的功能特性

期望可以将 fixture 当做为变量传递给实体函数.     

可以替代 httprunner 的 setup_hooks 和 teardown_hooks 功能.

## 示例描述（可选）

request_with_fixtures.yml 
```yaml
config:
    name: "request with fixture: session fixture"
    base_url: "https://postman-echo.com"
    fixture_as_param: ["session_fixture"]

teststeps:
-
    name: get with params
    request:
        method: GET
        url: /get
        params:
            info: "ip"
        headers:
            User-Agent: HttpRunner/${get_httprunner_version()}/${get_session_fixture($session_fixture)}

```

request_with_fixtures_test.py
```python3
# NOTE: Generated By HttpRunner v3.1.6
# FROM: request_methods/request_with_fixtures.yml


import debugtalk
import pytest


import allure


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseRequestWithFixtures(HttpRunner):
    @allure.title("request teststep: with error retry")
    def test_start(self, session_fixture):
        scope, fixtures = locals(), ["session_fixture"]
        values = map(lambda x: scope.get(x), fixtures)
        super().test_start(fixtures=dict(zip(fixtures, values)))

    config = Config("request teststep: with error retry").base_url(
        "https://postman-echo.com"
    )

    teststeps = [
        Step(
            RunRequest("get with params")
            .get("/get")
            .with_params(**{"info": "ip"})
            .with_headers(
                **{
                    "User-Agent": "HttpRunner/${get_httprunner_version()}/${get_session_fixture($session_fixture)}"
                }
            )
        ),
    ]


if __name__ == "__main__":
    TestCaseRequestWithFixtures().test_start()

```
