### ISSUE TITLE
按照jmespath文档[-1]提取最后一位,我提取出来的值是none

### ISSUE THREAD

**Issue by binbinu** [httprunner/httprunner#1171]
## 问题描述

按照jmespath文档[-1]提取最后一位,我提取出来的值是none,使用[1]可以提取出来值

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [e.g. macos]
 - Python 版本 [e.g. 3.6]
 - HttpRunner 版本 [e.g. 3.1.6]

yaml文件用例
```
config:
    name: 获取商品组合
    variables: {}
    verify: false
    base_url: '${ENV(HOST)}'
    export: [token, id]
teststeps:
-   name: get_token
    testcase: testcases/admin/login/login.yaml

-   name: /jeecg/itemGroup/itemGroupList
    request:
        headers:
            Version: ${ENV(VERSION)}
            X-Access-Token: ${token}
            appid: ${ENV(APPID)}
        method: GET
        params:
            current: '1'
            searchValue: ''
            size: '10'
        url: /jeecg/itemGroup/itemGroupList
    extract:
        id: body.result.records[-1].id
    validate:
    -   eq:
        - status_code
        - 200
    -   eq:
        - body.success
        - true
    -   eq:
        - body.message
        - 操作成功！
    -   eq:
        - body.code
        - 200

```

返回数据
```
body     : {
    "success": true,
    "message": "操作成功！",
    "code": 200,
    "result": {
        "records": [
            {
                "createtime": "2022-01-10 18:15:49",
                "mainimg": "",
                "name": "大礼包",
                "count": 3,
                "spu": "",
                "id": "9867367564588872",
                "updatetime": "2022-01-10 18:15:48",
                "status": 1
            },
            {
                "createtime": "2022-02-10 15:44:55",
                "mainimg": "",
                "name": "测试组合",
                "count": 2,
                "spu": "",
                "id": "98673675675612652",
                "updatetime": "2022-02-10 15:44:55",
                "status": 1
            },]

```

日志关键信息
```
2022-02-10 16:31:33.709 | INFO     | httprunner.response:extract:179 - extract mapping: {'id': None}
```
补充一个例子
![image](https://user-images.githubusercontent.com/51307123/158152770-95d3568d-9c6d-410f-8c47-f4c99c152b91.png)
![image](https://user-images.githubusercontent.com/51307123/158152779-10536a48-9877-45b2-8465-5e9981673438.png)
