### ISSUE TITLE
suite中执行顺序能否优化，求问api能执行多少次？

### ISSUE THREAD

**Issue by yxder** [HttpRunner/HttpRunner#119]
```
- api:
    def: api_baidu($a, $b)
    request:
        url: http://baidu.com
        method: GET
        params:
            a: $a
            b: $b
    validate:
        - eq: [status_code, 200]
```
---
```
- config:
    name: dsuite with a b
    def: dsuite_ab($a, $b)
    variables:
        - a: 1
        - b: 2

- test:
    name: test_cross_a_b{$a, $b}
    api: api_baidu($a, $b)
- test:
    name: test_a{$a, $b}
    variables:
        - a: 1
    api: api_baidu($a, $b)
- test:
    name: test_a{$a, $b}
    api: api_baidu($a, d)
```
---
```
- config:
    name: dtestcase
    parameters:
        - a: [1, 2, 3]
        - b: [a, b, c]

- test:
    name: test_1
    suite: dsuite_ab($a, $b)
```
