### ISSUE TITLE
引用用例提示$response变量找不到

### ISSUE THREAD

**Issue by binbinu** [httprunner/httprunner#1271]
```
config:
    name: 启用和禁用医院
    variables: {}
    verify: false
teststeps:
-   name: 查询医院管理
    testcase: testcases/运营平台/医院管理/医院管理/getAHospital.yml
    teardown_hooks:
        - ${is_hospital($response)}

```
关键日志
```
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/httprunner/parser.py:230: in get_mapping_variable
    return variables_mapping[variable_name]
E   KeyError: 'response'
```
