### ISSUE TITLE
v4 版本未自动加载 .env 文件

### ISSUE THREAD

**Issue by gaku1028** [httprunner/httprunner#1308]
## 问题描述

请问下4.1.beta版本，ENV里面的变量值是引用不了吗？

.env 里面只有一行值：uname_t=dagongsi

```yaml
config:
    name: testcase description
    variables:
        name: ${ENV(uname_t)}
```

但输出的值是空的： INF call function success arguments=["uname_t"] funcName=ENV output=

另外在env里面赋值一个普通的url，在赋值给base_url即base_url: ${ENV(url)}
提示": unsupported protocol scheme \"\""

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [e.g. Windows]
 - Python 版本: [e.g. 3.8.1]
 - Go 版本: [e.g. go1.18.2]
 - HttpRunner 版本 [e.g. HttpRunnerPlus v4.1.0-beta]

## 项目文件内容（非必须）

如果可能，提供项目测试用例文件原始内容可加快 bug 定位和修复速度。

提示：请注意在去除项目敏感信息（IP、账号密码、密钥等）后再进行上传。
