### ISSUE TITLE
4.1beta，在debugtalk.py中，有一个没有传参数的函数，提示函数is not found

### ISSUE THREAD

**Issue by gaku1028** [httprunner/httprunner#1309]
## 问题描述

> 请对 bug 进行简要描述；
> 
![image](https://user-images.githubusercontent.com/38396589/169692619-60eaae39-6a8f-4f46-aaf8-9ae41e58e995.png)
![image](https://user-images.githubusercontent.com/38396589/169692690-dcafe268-4a4c-4ab9-b297-f4df40bae9be.png)

config里面引用了函数name_t()

```yaml
config:
    name: testcase description
    variables:
       name: ${name_t()}
```

尝试用name_t(name):也不行，网上的例子都是以前版本的，类似于get_name()这样的没有参数的函数就可以，不知道4.1版本是什么情况。。。

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [e.g. Windows]
 - Python 版本: [e.g. 3.8.1]
 - Go 版本: [e.g. 1.18]
 - HttpRunner 版本 [e.g. 4.1beta]

## 项目文件内容（非必须）

如果可能，提供项目测试用例文件原始内容可加快 bug 定位和修复速度。

提示：请注意在去除项目敏感信息（IP、账号密码、密钥等）后再进行上传。
