### ISSUE TITLE
用于数据驱动的parameter解析bug

### ISSUE THREAD

**Issue by qparrow** [HttpRunner/HttpRunner#131]
版本:1.3.5

采用下列配置方式时,解析后的参数会变成 username为 ["user1", "111111"], password为空
```yaml
- config:
    parameters:
        - username-password:
            - ["user1", "111111"]
```
检查代码发现testcase.py 第654行的
`dict(zip(parameter_name_list, [parameter_item]))`zip的第二个参数不应该加一个`[]`而应该直接写`parameter_item`

```python
parameter_content_list = [
    dict(zip(parameter_name_list, [parameter_item]))
    for parameter_item in parameter_content
]
```
