### ISSUE TITLE
引用测试用例时参数驱动失效

### ISSUE THREAD

**Issue by jeremy8250** [httprunner/httprunner#1357]
## 问题描述

> 假设有个子用例A.yml，每次调用时返回传入的参数“TREATMENTNO”，比如传123返回123，传456返回456，内容如下：
```
config:
    name: “子用例A”
    base_url: ${ENV(DOMAIN)}
    verify: False

teststeps:
-
    name: "处理单号”
    request:
        method: POST
        url: /srs/submit
        headers:
            content-type: "application/json;charset=UTF-8"
        json:
            treatmentNo: $TREATMENTNO
    validate:
        - eq: ["status_code", 200]
```

>现在有个主用例B.yml,多次调用A,只是每次传递的参数不同
```
config:
    name: "主用例B”
    base_url: ${ENV(DOMAIN)}
    verify: False

teststeps:
-
    name: "处理单号1”
    variables:
        TREATMENTNO: “ABC123”
    testcase: testcases/A.yml

-
    name: "处理单号2”
    variables:
        TREATMENTNO: “abc456”
    testcase: testcases/A.yml

```

>当第二次调用A.yml的时候，应该返回abc456，实际还是返回ABC123。

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [macOS]
 - Python 版本: [3.7.7]
 - Go 版本: [none]
 - HttpRunner 版本 [3.1.4]

## 项目文件内容（非必须）

如果可能，提供项目测试用例文件原始内容可加快 bug 定位和修复速度。

提示：请注意在去除项目敏感信息（IP、账号密码、密钥等）后再进行上传。
