### ISSUE TITLE
断言自定义函数不支持中文参数

### ISSUE THREAD

**Issue by kaixinbaba** [httprunner/httprunner#1644]
## 问题描述

> 断言自定义函数不支持中文参数
case 配置
```yml
    ... 其他省略
    validate:
       - eq: ["${customer_assert(中文, 中文)}", 1]

```
python 函数
```python
# 示例函数
def customer_assert(data, value):
    return 1 if data == value else 0
```
会得到报错信息
![image](https://github.com/httprunner/httprunner/assets/22809336/1de2d32a-aac7-4ff3-a524-968f8fb9f544)

但是换成 英文的 就不会报错了 
```yml
    ... 其他省略
    validate:
       - eq: ["${customer_assert(zhongwen, zhongwen)}", 1]

```
![image](https://github.com/httprunner/httprunner/assets/22809336/78c214c1-1113-4c90-9c83-24f749d89c66)

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [e.g. macOS]
 - Python 版本: [e.g. 3.9.12]
 - Go 版本: [e.g. 1.19]
 - HttpRunner 版本 [e.g. 4.3.0]

期待您的回复
