### ISSUE TITLE
框架中集成文件上传功能

### ISSUE THREAD

**Issue by debugtalk** [httprunner/httprunner#169]
针对常见的文件上传场景，在框架中集成为内置功能。

#23 #103 #144

**Comment by debugtalk** [comment]
在框架中内置 `multipart_encoder` 和 `multipart_content_type` 函数，具体使用方式如需：

```yaml
- config:
    name: test upload file with httpbin
    request:
        base_url: https://httpbin.org

- test:
    name: upload file
    variable_binds:
        - field_name: "file"
        - file_path: "LICENSE"
        - file_type: "text/html"
        - multipart_encoder: ${multipart_encoder($field_name, $file_path, $file_type)}
    request:
        url: /post
        method: POST
        headers:
            Content-Type: ${multipart_content_type($multipart_encoder)}
        data: $multipart_encoder
    validators:
        - eq: ["status_code", 200]
        - startswith: ["content.files.file", "MIT License"]
```

**Comment by jinjie2088** [comment]
你好，上传文件报以下错：
ERROR: runTest (httprunner.task.TestCase)
upload file
----------------------------------------------------------------------
Traceback (most recent call last):
VariableNotFound: multipart_encoder not found in recursive upward path!

以下是我的测试yaml文件：
- test:
   name: upload file
   request:
       variable_binds:
          - field_name: "file"
          - file_path: "D:\002.xlsx"
          - file_type: "text/html"
          - multipart_encoder: ${multipart_encoder($field_name, $file_path, $file_type)}
       url: /terminal-device-service/v1/temp-files
       method: POST
       headers:
          Authorization: "Bearer $Authorization"
          Content-Type: ${multipart_content_type($multipart_encoder)}
       data: $multipart_encoder

**Comment by julianmail** [comment]
使用上面代码，报错：multipart_encoder is not defined in bind    @@@functions!是什么问题？
测试脚本如下：
- config:
    name: test upload file with httpbin

- test:
    name: upload file
    variable_binds:
        - field_name: "xmlfile"
        - file_path: "D:\\Dev\\httprunner\\HttpRunner-master1.4.1\\HttpRunner-master\\examples"
        - file_type: "text/xml"
        - multipart_encoder: ${multipart_encoder($field_name, $file_path, $file_type)}
    request:
        url: http://jobws.push.mobile.xxxxxxxx.com/RefreshWeiXInTokenJob/RefreshService.asmx
        method: POST
        headers:
            Content-Type: ${multipart_content_type($multipart_encoder)}
        data: $multipart_encoder
    validators:
        - eq: ["status_code", 200]

**Comment by debugtalk** [comment]
@julianmail 你用的版本是？

**Comment by julianmail** [comment]
现在用的是1.4.1的版本

**Comment by strayberry** [comment]
一个请求内上传两个文件的话data的写法应该是怎么样的呢

**Comment by jcuan** [comment]
其实可以直接使用request提供的文件上传功能

```yml
- test:
    name: file
    variables:
        - file_path: d:\code\python\worktest\test.py
        - mode: 'rb'
    request:
        url: /
        method: POST
        data: #表单数据
            name: jcuan
        files: #文件数据
            fileKey: 
                - test.html #文件名
                - ${open($file_path,$mode)}	#文件内容，通过open打开
                - text/html #content-type
```

**Comment by debugtalk** [comment]
@jcuan 这种方式在解决 #418 之前是不行的。在解决之后我还没试过，你有测试过么？

**Comment by jcuan** [comment]
@debugtalk 原来是这样，我这边是正常的

win 10
python 3.7.1
httprunner 1,5.14

```
================== request details ==================
url              : 'http://127.0.0.1/'
method           : 'POST'
headers          : {'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Host': 'jcuan.xyz', 'Content-Length': '1960', 'Content-Type': 'multipart/form-data; boundary=f9f42fe8911c4000bba3f5aee2057a62'}
start_timestamp  : 1541044111.9319515
verify           : False
data             : {'name': 'jcuan'}
files            : {'fileKey': ['test.html', <_io.BufferedReader name='d:\\code\\python\\worktest\\test.py'>, 'text/html']}
```

**Comment by holysor** [comment]
请问如何在上传文件，同时在data上加入参数

**Comment by huiCSDN** [comment]
> 请问如何在上传文件，同时在data上加入参数
> ![image](https://user-images.githubusercontent.com/17400810/49214375-7df2aa00-f401-11e8-9040-2eb33dc3894d.png)

您好，你这个上传文件时，再添加其他参数的问题解决了吗

**Comment by dreamer1314** [comment]
httprunner版本：2.0.5
执行上面的demo,报找不到
VariableNotFound: multipart_encoder is not found.[
<img width="675" alt="屏幕快照 2019-04-22 下午7 24 11" src="https://user-images.githubusercontent.com/13436608/56498851-2b439700-6536-11e9-8095-0622f330bf99.png">
](url)

**Comment by dreamer1314** [comment]
httprunner版本：2.0.5
执行上面的demo,报找不到
VariableNotFound: multipart_encoder is not found.
<img width="780" alt="屏幕快照 2019-04-22 下午8 15 51" src="https://user-images.githubusercontent.com/13436608/56499962-71e7c000-653b-11e9-97dd-e4847328bff9.png">

**Comment by xtander** [comment]
和楼上一样的版本一样的问题，VariableNotFound: multipart_encoder is not found

**Comment by weigun** [comment]
> 一个请求内上传两个文件的话data的写法应该是怎么样的呢

有解决方法了吗？我也需要上传多个文件呢

**Comment by ouylongzhou** [comment]
@jcuan    麻烦问下，我的环境跟你的差不多，上传文件失败，files跟你的一样，但在前端查看请求files内容为空的
##########################打印的格式请求##########################
{'name': '上传文件至file service', 'times': 1, 'request': {'url': 'https://storage-qa.pg.com.cn/v1/files',
'method': 'POST', 'verify': False, 'headers': {'Origin': 'https://goldeninvestorqa.pg.com.cn', 'Referer': 'https://goldeninvestorqa.pg.com.cn/', 'Accept-Encoding': 'gzip, deflate'}, 'd
ata': {'subscriptionKey': 'gi-fund', 'public': 'false', 'signature': '$sign', 'timestamp': '$timeStamp'}, 

'files': {'file': ['1.png', <_io.BufferedReader name='D:/Runner/Runner/static/images/1.png'>, 'image/png']}},

 'desc': {'header': {'Origin': '', 'Referer': '', 'Accept-Encoding': ''}, 'data': {'subscriptionKey': '', 'public': '', 'signature': '', 'timestamp':
 ''}, 'files': {'file': ''}, 'params': {}, 'variables': {}, 'extract': {}}

#######################前端页面操作的请求###########################
"verify": false,
  "data": {
    "subscriptionKey": "gi-fund",
    "public": "false",
    "signature": "19225f801997cf35ea6758718961c645bff3f099",
    "timestamp": 1560929412000
  },
  "files": {
    "file": [
      "1.png",
      [],
      "image/png"
    ]
  },

**Comment by jcuan** [comment]
@ouylongzhou  我刚刚又试了一下是可以的，你没有设置content-type吧（不能设置，否则会缺少boundary）？

```yml
- config:
    name: local test
    request:
        base_url: http://127.0.0.1:8000
        verify: false
        headers:
            User-Agent: python-requests/2.18.4


- test:
    name: file
    variables:
        - file_path: /Users/jcuan/code/python/httprunner/file.txt
        - mode: 'rb'
    request:
        url: /
        method: POST
        data: 
            name: jcuan
        files: 
            fileKey: 
                - fileRename.txt
                - ${open($file_path,$mode)}
                - text/plain
```

server收到的信息， 文本表单、文件、还有文件内容都是正常的
```
Array
(
    [name] => jcuan
)
Array
(
    [name] => fileRename.txt
    [type] => text/plain
    [tmp_name] => /private/var/folders/c8/9lrr5s1j3cdbxr2k7jlhtg2m0000gp/T/phpQ9wSqL
    [error] => 0
    [size] => 22
)

file content for test!
```

**Comment by ouylongzhou** [comment]
没有设置content-type，  你那边正常，页面请求files是怎样的 ？   我这边files 中对象是空的 与 解码时 设置了参数  ignore 有关吗？  





------------------ 原始邮件 ------------------
发件人: "jcuan"<notifications@github.com>;
发送时间: 2019年6月20日(星期四) 凌晨1:20
收件人: "HttpRunner/HttpRunner"<HttpRunner@noreply.github.com>;
抄送: "追梦"<156746694@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [HttpRunner/HttpRunner] 框架中集成文件上传功能 (#169)




@ouylongzhou  我刚刚又试了一下是可以的，你没有设置content-type吧（不能设置，否则会缺少boundary）？
 - config:     name: local test     request:         base_url: http://127.0.0.1:8000         verify: false         headers:             User-Agent: python-requests/2.18.4 - test:     name: file     variables:         - file_path: /Users/jcuan/code/python/httprunner/file.txt         - mode: 'rb'     request:         url: /         method: POST         data:              name: jcuan         files:              fileKey:                  - fileRename.txt                 - ${open($file_path,$mode)}                 - text/plain
 
server收到的信息， 文本表单、文件、还有文件内容都是正常的
 Array (     [name] => jcuan ) Array (     [name] => fileRename.txt     [type] => text/plain     [tmp_name] => /private/var/folders/c8/9lrr5s1j3cdbxr2k7jlhtg2m0000gp/T/phpQ9wSqL     [error] => 0     [size] => 22 ) file content for test!

**Comment by hstart** [comment]
1、jcuan 说的是正解。
2、从httprunner的源码来看，底层用的是requests.Session.request 这个来发送http请求。
3、而且 requests.Session.request 中参数恰好是 测试文件里面所配置的，换位dic格式 ，所以依据requests.Session.request 输入参数，可以直接在测试案例里面添加 files 这个字段。
4、使用的是注意的地方是 **案例里面不要配置Content-type 字段**，否则会出现问题。原因是如果是files参数，request会自动在header里面添加相关参数，不用人工添加。
5、以下是一个例子：
    request:
        headers:
            User-Agent:Android Client
        method: POST
        url: http://xxx.xx.xx.xx//upload
        files: 
            chnCode: 
                -
                - TEST
            fileDesc:
                -
                - HUAWEI NXT-AL10
            filecontent: 
                - $file_name
                - ${open(file.dat)}
                - application/octet-stream
 6、例子说明：对于非文件参数，**则第一个参数留空，第二参数才是值**，对于json 格式 空用null字符代替。
7、files 的参数类型常用以下几种方式。
{
 “field1”:(名称,值,类型)
“field1”:(None,“字符串值”)
“field1”:("1.jpg",open("1.jpg"),"image/jpg")
}

**Comment by debugtalk** [comment]
@hstart 使用 requests files 进行上传会存在问题，当上传文件非常大的时候，占用内容会非常高。

> In the event you are posting a very large file as a multipart/form-data request, you may want to stream the request. By default, requests does not support this, but there is a separate package which does - requests-toolbelt. You should read the toolbelt’s documentation for more details about how to use it.

> Requests has support for multipart uploads, but the API means that using that functionality to build exactly the Multipart upload you want can be difficult or impossible. Additionally, when using Requests’ Multipart upload functionality all the data must be read into memory before being sent to the server. In extreme cases, this can make it impossible to send a file as part of a multipart/form-data upload.

https://toolbelt.readthedocs.io/en/latest/uploading-data.html#streaming-multipart-data-encoder
https://2.python-requests.org//en/latest/user/quickstart/#post-a-multipart-encoded-file

**Comment by debugtalk** [comment]
最终方案：https://docs.httprunner.org/prepare/upload-case/


对于上传文件类型的测试场景，HttpRunner 集成 [requests_toolbelt][1] 实现了上传功能。

在使用之前，确保已安装如下依赖库：

- [requests_toolbelt](https://github.com/requests/toolbelt)
- [filetype](https://github.com/h2non/filetype.py)

使用内置 `upload` 关键字，可轻松实现上传功能（适用版本：2.4.1+）。

```yaml
- test:
    name: upload file
    request:
        url: http://httpbin.org/upload
        method: POST
        headers:
            Cookie: session=AAA-BBB-CCC
        upload:
            file: "data/file_to_upload"
            field1: "value1"
            field2: "value2"
    validate:
        - eq: ["status_code", 200]
```

同时，你也可以继续使用之前描述形式（适用版本：2.0+）。

```yaml
- test:
    name: upload file
    variables:
        file: "data/file_to_upload"
        field1: "value1"
        field2: "value2"
        m_encoder: ${multipart_encoder(file=$file, field1=$field1, field2=$field2)}
    request:
        url: http://httpbin.org/upload
        method: POST
        headers:
            Content-Type: ${multipart_content_type($m_encoder)}
            Cookie: session=AAA-BBB-CCC
        data: $m_encoder
    validate:
        - eq: ["status_code", 200]
```

参考案例：[httprunner/tests/httpbin/upload.v2.yml][2]

[1]: https://toolbelt.readthedocs.io/en/latest/uploading-data.html
[2]: https://github.com/httprunner/httprunner/blob/master/tests/httpbin/upload.v2.yml
