### ISSUE TITLE
yml用例中，自定义函数无法嵌套执行

### ISSUE THREAD

**Issue by chenhuahuan** [HttpRunner/HttpRunner#179]
`${get_trimmed_lt_for_login( ${test_embeded()} )}`中，无法执行最外层的`get_trimmed_lt_for_login()`函数，httprunner只执行了`test_embeded()`函数。请看下怎么解决。谢谢。

**Comment by debugtalk** [comment]
HttpRunner 识别函数和变量是基于正则表达式，这样嵌套的方式的确识别不出来。

你可以分两次来实现：

```yaml
variables:
    - var: "${test_embeded()}"
    - result: "${get_trimmed_lt_for_login($var)}"
```
