### ISSUE TITLE
数据驱动的问题

### ISSUE THREAD

**Issue by wjian2580** [HttpRunner/HttpRunner#186]
您好，如何实现给不同的参数绑定相应的校验器，毕竟不同的入参会导致不同的响应，到头来还是要写几个test

**Comment by debugtalk** [comment]
在校验器中是可以引用变量的。

**Comment by JacobHZ** [comment]
校验器引用变量？有示例么，我没看懂...

我现在都是分正向、反向用例，每次写多条test。

**Comment by wjian2580** [comment]
@JacobHZ 

我好像明白了 ，可以将你的参数列表依次传入一个你自定义的函数。根据这个函数返回预期的结果，这样就可以只写一条测试用例了。这个函数是放在debugtalk.py中，然后在校验器中调用。

例如 ：

```
parameters:
    item: ['1','2','3']


    validate:
        - {"check": "content.checkitem", "comparator": "eq", "expect": ${check_item(request.item)}}
```

下面是debugtalk.py中定义的方法

```
def check_item(item):
    if item == '1':
          expected = a
    ..........

    return expected
```
