### ISSUE TITLE
请求 data 的 dump 处理机制

### ISSUE THREAD

**Issue by debugtalk** [HttpRunner/HttpRunner#191]
当请求 headers 的 Content-Type 为 application/json 时，会对 data 进行 dumps 操作。

但当请求 data 为字符串而非 JSON 结构时，会造成请求的内容多了一层双引号。

```
- test:
    name: post data
    request:
        url: /post
        method: POST
        headers:
            Content-Type: application/json
        data: abc
    validate:
        - eq: ["status_code", 200]
```

即 abc => "abc"。
