### ISSUE TITLE
如何从Response中提取list中的值

### ISSUE THREAD

**Issue by Xhao123456** [HttpRunner/HttpRunner#20]
如果一个testcase的response中content的kv值中v里面包含数组，这种value值可以取出来作为另一个testcase的request吗？

**Comment by Xhao123456** [comment]
比如这种形式{"resultCode":"1001","friendAndShareDeviceMsg":[{"userIDS":152,"msgTypeID":2,"msgID":2683},{"userIDS":152,"msgTypeID":2,"msgID":2587}]}我如何在另一个testcase里面使用这个testcase返回的msgID

**Comment by debugtalk** [comment]
@Xhao123456 可以的。

按照你的例子，假如我们要取list中第一个元素的msgID，那么就可以按照这种方式：

`content. friendAndShareDeviceMsg.0.msgID`，

而如果是取第二个元素的msgID，那么就是：

`content. friendAndShareDeviceMsg.1.msgID`

**Comment by Xhao123456** [comment]
如果要同时提取所有的list呢，但是具体list的长度要根据之前一个testcase的返回值来确定，该怎么获取

**Comment by debugtalk** [comment]
@Xhao123456 

从你描述的这三个需求来看，都是非常规需求，所以不会在框架层面实现，但是你都可以通过结合Python函数的形式来实现。

例如，单独写一个函数，可以实现你的数据处理需求。

```python
# file name: mymodule.py

def get_all_msgIDs(friendAndShareDeviceMsg):
    return [item['msgID'] for item in friendAndShareDeviceMsg]

def get_msgTypeID_by_msgID(friendAndShareDeviceMsg, msgID):
    for item in friendAndShareDeviceMsg:
        if item['msgID'] == msgID:
            return item['msgTypeID']

    return 0
```

然后在你的测试用例中导入该函数模块，就可以根据需求进行调用了。

```yaml
- test:
    name: first-testcase
    request:
        url: /get-response
        method: GET
    extract_binds:
        - friendAndShareDeviceMsg: content.friendAndShareDeviceMsg
    validators:
        - {"check": "status_code", "expected": 200}
        - {"check": "content.resultCode", "expected": "1001"}

- test:
    name: latter-testcase
    import_module_functions:
        - mymodule
    request:
        url: /latter-handling
        method: GET
        data:
            msgIDs: ${get_all_msgIDs($friendAndShareDeviceMsg)}
            msgTypeID: ${get_msgTypeID_by_msgID($friendAndShareDeviceMsg, 2587)}
    validators:
        - {"check": "status_code", "expected": 200}
```

通过上面这种方式，应该就可以实现你的三个需求了。

后续如果有其它类型的复杂场景，也都可以采用类似的思路。
