### ISSUE TITLE
testcases下定义了用例参数，运行提示找不到参数

### ISSUE THREAD

**Issue by wuyajun2016** [HttpRunner/HttpRunner#210]
testcases文件下，存在以下用例smoketest.yml：

```yaml
- config:
    name: smoketest
    request: $default_request  
- test:
    name: 错误账密登录测试
    parameters:
        - userid-password:
            - ["xxx", "xxx"]
    suite: loginSuite($userid, $password)
```

suite文件下，存在以下：

```yaml
- config:
    name: "suittest"
    def: loginSuite($userid, $password)
    request: $default_request
- test:
    name: 获取token
    api: login($userid, $password)
```

api文件下，存在以下：

```yaml
- api:
    def: login($userid, $password) 
    request:
      url: 'xxx'
      headers: {}
      method: POST
      data:
        simpleAccountService.login: |-
          {
            "areaCode" : "86",
            "password" : "$password",
            "userid" : $userid,
            }
          }
```

为啥hrun tests/testcases/smoketest.yml时候提示httprunner.exception.VariableNotFound: password not found in recursive upward path!，求指教
