### ISSUE TITLE
parameters 中调用函数报错

### ISSUE THREAD

**Issue by BensonMax** [HttpRunner/HttpRunner#226]
需求：
### 字符串拼凑：
      目标字符串：`ibeiliao-parent-android-Beiliao(Android/Parent_4.22.0);hongying`
      我写的生成字符串的函数：
```
def get_parent_userAgent(band):
    userAgent = "ibeiliao-parent-android-Beiliao(Android/Parent_4.22.0);"+band
    print (userAgent)
    return userAgent 
```
### 调用部分和报错：
![_20180513130833](https://user-images.githubusercontent.com/31434954/39964100-1784b960-56af-11e8-87c9-98f92c591664.png)

**Comment by debugtalk** [comment]
@BensonMax 当前在 parameters 中是无法调用函数的。不过你可以通过如下方式绕过：

1、在 variables 中定义一个变量，变量的值为调用函数；
2、在 parameters 中引用该变量。

```yaml
- config:
    variables:
         - userAgent: ${get_parent_userAgent('hongying')}
    parameters:
        - teacher-userAgent:
            - ["0", $userAgent]
```
