### ISSUE TITLE
如何实现上传文件或图片？

### ISSUE THREAD

**Issue by Xhao123456** [HttpRunner/HttpRunner#23]
请教下，如果要以多文件上传图片，在yaml的格式是怎样的？
例如：图片路径为/home/work/favimg.jpg, file-tuple为2-tuple，（‘filename’，fileobj）

**Comment by debugtalk** [comment]
@Xhao123456 可以使用`requests_toolbelt`的`MultipartEncoder`实现。

先看单文件的情况：在Python模块中实现构造上传信息。

```python
from requests_toolbelt import MultipartEncoder

def make_user_info(avatar_file):
    fields = {
        'avatar': ('filename', open(avatar_file, 'rb'), 'image/jpeg'),
    }
    return MultipartEncoder(fields)

def get_content_type(multipart_encoder):
    return multipart_encoder.content_type
```

然后就可以在测试用例中调用了。

```yaml

- test:
    name: register
    variable_binds:
        - avatar_file: "/Users/Leo/Pictures/Snip20170523_24.png"
        - multipart_encoder: ${make_user_info($avatar_file)}
    request:
        url: /api/v1/users
        method: POST
        headers:
            Content-Type: ${get_content_type($multipart_encoder)}
            Accept: application/json
            Token: $TOKEN
        data: $multipart_encoder
    validators:
        - {"check": "status_code", "comparator": "eq", "expected": 201}
        - {"check": "content.status", "comparator": "eq", "expected": 0}
```

至于怎么上传多个文件，思路是一样的，都是使用`requests_toolbelt`，可以查看对应的文档。
