### ISSUE TITLE
用这个demo 生成出来的repoort 会自动跳转到 api_url

### ISSUE THREAD

**Issue by BensonMax** [httprunner/httprunner#239]
```
- api:
    def: api_baidu($a, $b)
    request:
        url: http://baidu.com
        method: GET
        params:
            a: $a
            b: $b
    validate:
        - eq: [status_code, 200]

```

```
- config:
    name: dsuite with a b
    def: dsuite_ab($a, $b)
    variables:
        - a: 1
        - b: 2

- test:
    name: test_cross_a_b{$a, $b}
    api: api_baidu($a, $b)
- test:
    name: test_a{$a, $b}
    variables:
        - a: 1
    api: api_baidu($a, $b)
- test:
    name: test_a{$a, $b}
    api: api_baidu($a, d)
```

![image](https://user-images.githubusercontent.com/31434954/40213751-b2a5fbec-5a89-11e8-9286-c649ba61f564.png)

### 点击后打开
![image](https://user-images.githubusercontent.com/31434954/40213777-d8e410e6-5a89-11e8-95ae-8ab1ebdc0bfa.png)
### 约0.3秒后跳转
![image](https://user-images.githubusercontent.com/31434954/40213762-c1d74bde-5a89-11e8-8b4a-499346202b84.png)
