### ISSUE TITLE
报告展示错误

### ISSUE THREAD

**Issue by yinquanwang** [HttpRunner/HttpRunner#248]
```yml
- config:
    name: base_url config
    request: 
      base_url: 'http://192.168.91.45'

- test:
    name: test_login_1
    request:
      url: /api/test_login/
      method: POST
      data: 
        username: lcc
        password: lcc
    validate:
      - {comparator: equals, check: content.code, expected: success}
      - {comparator: equals, check: content.status, expected: true}

- test:
    name: test_deposit
    request:
      url: /api/test_deposit/
      method: POST
      data: 
        code: $code
        money: '1'
    validate:
      - {comparator: equals, check: content.code, expected: error}
      - {comparator: equals, check: content.status, expected: false}
```

![image](https://user-images.githubusercontent.com/32924136/40407957-95789dbe-5e98-11e8-822c-b6627e23260f.png)
![image](https://user-images.githubusercontent.com/32924136/40407968-a20b6b38-5e98-11e8-9fee-5bbe254cb78e.png)
对于引用未经定义的code，或者调用不存在的hook函数，第二条用例会执行第一条用例的信息
报告里面名字是对的 但是响应时间还有log里面都是test_login的信息
