### ISSUE TITLE
配置parameters参数化时，没有调用相应参数的，也重复执行了

### ISSUE THREAD

**Issue by master-walker** [HttpRunner/HttpRunner#258]
```yaml
- config:
    parameters:
        - srcArr: ["test", "test2"]
    variables:
        - phone: 10086
        - src: app

- test:
    name: test1
    api: get_code($phone, ,$srcArr)
    validate:
        - eq: [status_code, 200]

- test:
    name: test2
    api: get_code($phone, ,$src)
    validate:
        - eq: [status_code, 200]
```

本来应该执行3次，2条报告， 实际执行了4次，4条报告
再加一条的话       - msgTypeArr: ["0", "1"]   没有调用到，还会重复执行相应的倍数次
