### ISSUE TITLE
调用函数的参数中包含空格时，空格会被自动去除

### ISSUE THREAD

**Issue by chenchengyuan** [HttpRunner/HttpRunner#260]
请帮忙看一下
1、例如${aa(delete from)}，解析到的为 deletefrom
2、例如${aa("delete from")}，怀疑没有进入函数
![20180530_001](https://user-images.githubusercontent.com/29788128/40694926-6a1bd20e-63f1-11e8-98f9-b644b5328cb1.png)

```python
def aa(sql):
      return sql
```

**Comment by debugtalk** [comment]
@chenchengyuan 这的确是个bug。在匹配函数和参数时，会将空格去掉，我后面看下怎么修复吧。
你当前可以采用绕过的方式：

```yaml
variables:
    - data: delete from
    - device_sn: ${aa($data)}
```
