### ISSUE TITLE
parameters里取前一个接口响应的数据不行吗，还是姿势不对？

### ISSUE THREAD

**Issue by master-walker** [HttpRunner/HttpRunner#266]
```
- test:
    name: 查询
    api: test1()
    validate:
        - eq: [status_code, 200]
    extract:
        - industryIds : content.data

- test:
    name: 查询列表
    parameters:
        - industryId: ${parse_industry_id($industryIds)}
    api: test2($industryId)
    validate:
        - eq: [status_code, 200]
```

执行后，报 httprunner.exception.VariableNotFound: industryIds not found in recursive upward path!
