### ISSUE TITLE
请教一下，debugtalk.py中函数返回2个值，在用例中怎么调用

### ISSUE THREAD

**Issue by chenchengyuan** [HttpRunner/HttpRunner#276]
例如

```python
def m():
    a = 1
    b = a+1
    return a,b
```

试了一下，${m()}[0]和${{m()}[0]}都取不到a的值
请问可以支持类似的方式吗？

**Comment by debugtalk** [comment]
@chenchengyuan 不支持调用函数返回多个值的情况。

针对你的需求，你可以再增加一个函数：

```python
def get_value(origin_list, index):
    return origin_list[index]
```

然后在需要调用的时候：

```yaml
variables:
    - values: ${m()}
    - a: ${get_value($values, 0)}
    - b: ${get_value($values, 1)}
```
