### ISSUE TITLE
接口是利用aksk方式加密的，怎么调用

### ISSUE THREAD

**Issue by grizz622** [HttpRunner/HttpRunner#311]
aksk加密，就是把本次请求的下列四个信息
1、POST /getToken
2、Host: 127.0.0.1:5201
3、Content-Type: application/json
4、请求Body：{"flag":"test","appId":"001"}
根据1-4的值和给定的AK和SK的值，加密得到秘钥放到本次请求的headers中

httprunner怎么extract出本次请求的url，请求body等值

```
- test:
    name: /api/get-token
    request:
        url: /api/get-token
        method: POST
        headers:
            app_version: $app_version
        json:
            sign: ${get_sign($user_agent, $device_sn, $os_platform, $app_version)}
    extract:
        - token: content.token
    validate:
        - eq: [status_code, 200]
```
