### ISSUE TITLE
Testcases not found

### ISSUE THREAD

**Issue by zhangliping2** [HttpRunner/HttpRunner#319]
使用运行一个demo一直报错，各种改了还是不行，已经耗着两天没进度，求指点
C:\Users\PH>hrun E:\ApiTest\tests\testcases\kuaidi.yml
ERROR    Testcases not found in ['E:\\ApiTest\\tests\\testcases\\kuaidi.yml']

测试用例：

```yaml
- config:
  name: test_demo
  request:
    base_url: http://www.kuaidi100.com
    headers:
      User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100Safari/537.36

- test:
  name: /query
  request:
    url: /query
    method: GET
    json:
      type: huitongkuaidi
      postid: 350757819118
    
  validate:
    - eq: ["status_code",200]
    - eq: ["headers.Content-Type",text/html;charset=UTF-8]
    - eq: ["content.nu",50757819118]
```
