### ISSUE TITLE
带中文参数请求会转为unicode

### ISSUE THREAD

**Issue by BensonMax** [httprunner/httprunner#395]
## 问题描述
带中文参数请求会转为unicode
```
- api:
    def: ChangeOrder($express_nbr, $cust_order_id, $item_id)
    request:
        url: /api/open/r/expressdelivery/ChangeOrder
        method: POST
        json:
            cust_id: 36281276A***************
            exp_type: 0
            params:
            -   change_type: "0"
                cust_order_id: $cust_order_id
                express_nbr: $express_nbr
                item_id: $item_id
                scust_addr: "氪空间"
```
请求时候中文参数会转码成为unicode
```
{"cust_id": "36281276A***************", "exp_type": 0, "params": [{"change_type": "0", "cust_order_id": "01037100888", "express_nbr": "1117825001013", "item_id": "193342", "scust_addr": "\u6c2a\u7a7a\u95f4"}]}
```

## 实验案例
```
-   config:
        name: testset description
        request:
            headers:
                User-Agent: PostmanRuntime/7.3.0
        variables: []
-   test:
        name: /signature/GetPSignature
        request:
            headers:
                Content-Type: application/json
                Postman-Token: d9cc50ca-8a73-46fb-99b7-596adc306152
            json:
                ukey: 测试
                user_id: '4'
            method: POST
            url: http://******************/signature/GetPSignature
        validate:
        -   eq:
            - status_code
            - 404
```

## 抓包结果
用postman请求
```
{
	"ukey": "测试",
	"user_id": "4"
}
```
用httprunner请求
```
{
	"ukey": "\u6d4b\u8bd5",
	"user_id": "4"
}
```

请提供如下版本信息：

 - 操作系统类型: Windows 7/10
 - Python 版本 Python 3.6.5 :: Anaconda, Inc.
 - HttpRunner 版本 1.5.2 \ 1.5.8 \1.5.12

**Comment by BensonMax** [comment]
```
-   config:
        name: testset description
        request:
            base_url: ''
            headers:
                User-Agent: python-requests/2.18.4
        variables: []
-   test:
        name: {{api}}test
        request:
            data: '{"name":"中二","content":"病"}'
            headers:
                Content-Type: text/plain
            method: POST
            url: http://{{api}}/AddTemplate
        validate:
        -   eq:
            - status_code
            - 200
```

问题解决
![image](https://user-images.githubusercontent.com/31434954/47647801-156e9e00-dbb3-11e8-8eab-94e244de6745.png)
