### ISSUE TITLE
对于parser.py文件中的正则表达式的修改建议

### ISSUE THREAD

**Issue by chinatallyman** [httprunner/httprunner#437]
在parser.py文件中对于下面两个正则表达式，我在其中增加了对 : 和 \ 的匹配。
function_regexp = r"\$\{([\w_]+\([\$\w\.\-/_ =,:\\]*\))\}"
function_regexp_compile = re.compile(r"^([\w_]+)\(([\$\w\.\-/_ =,:\\]*)\)$")
我这样做的目的是：增加对Windows平台的文件路径的支持。
例如下面的代码，我在parameters中通过绝对路径的方式指定csv文件，但是原正则，不会匹配 : 和  \ ，所以这样指定csv文件会报错，即不支持windows平台的路径书写方式。

```yaml
- config:
    name: "user management testset."
    def: register()
    parameters:
        - user_agent: ["iOS/10.1", "iOS/10.2", "iOS/10.3"]
        - username-password: ${P(C:\Users\xcc\Desktop\workspace-eric6\tests\testcases\account.csv)}
        - uid: ["1001","1002"]
    variables:
        - device_sn: ${gen_random_string(15)}
        - os_platform: 'ios'
        - app_version: 2.8.5
        - BASE_URL: "http://127.0.0.1:5000"
    request:
        base_url: $BASE_URL
        headers:
            Content-Type: application/json
            device_sn: $device_sn
```
