### ISSUE TITLE
verify 的设置方式

### ISSUE THREAD

**Issue by wanghao828309** [HttpRunner/HttpRunner#486]
## 问题描述
例如：
requests.get('https://192.168.100.4',headers={'Host':'test.com'},verify=False)
如下请求的verify=False怎么在yaml文件里写

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [e.g. macos, Linux, Windows]
 - Python 版本 [e.g. 3.6]
 - HttpRunner 版本 [e.g. 1.5.11]

## 堆栈信息

请提供出现 bug 时的详细堆栈内容。

## 项目文件结构

请提供测试用例的文件组织结构。比较好的方式是在项目根目录中执行`tree -a`命令。

## 项目文件内容（非必须）

如果可能，提供项目测试用例文件原始内容可加快 bug 定位和修复速度。

提示：请注意在去除项目敏感信息（IP、账号密码、密钥等）后再进行上传。

**Comment by 406722575** [comment]
- config:
     headers:
       verify: False
试试这样，要不就是和url同一层

**Comment by debugtalk** [comment]
verify 可以在 config 设置（全局生效），也可以在 test 的 request 中设置（当前 test 有效）。

```YAML
- config:
    name: XXX
    verify: False

- test:
    name: XXX
    request:
        url: XXX
        verify: False
```
