### ISSUE TITLE
参数化数据驱动文档更新

### ISSUE THREAD

**Issue by TesterChen** [HttpRunner/HttpRunner#488]
## 问题描述

数据参数化不生效，无法执行所有数据，取不到变量user_id

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [macos,]
 - Python 版本 [3.6]
 - HttpRunner 版本 [2.0.0]

## 项目文件内容（非必须）

```yaml
- config:
    name: testcase description
    base_url: http://127.0.0.1:5000
    parameters:
        - user_id: ["1001", "1002"]
    variables:
        - device_sn: ${gen_random_string(15)}
        - user_agent: "iOS/10.3"
        - os_platform: "ios"
        - app_version: "2.8.6"

- test:
    name: /api/get-token
    request:
        url: /api/get-token
        method: POST
        headers:
            device_sn: $device_sn
            Content-Type: application/json
            app_version: $app_version
            os_platform: $os_platform
            user_agent: $user_agent
        json:
            sign: ${get_sign($user_agent, $device_sn, $os_platform, $app_version)}
    extract:
        - token: content.token
    validate:
        - eq: [status_code, 200]
        - eq: [headers.Content-Type, application/json]
        - eq: [content.success, true]

- test:
    name: /api/users/$user_id
    request:
        url: /api/users/$user_id
        method: POST
        headers:
            device_sn: $device_sn
            token: $token
        json:
            name: user1
            password: '123456'
    validate:
        - eq: [status_code, 201]
        - eq: [headers.Content-Type, application/json]
        - eq: [content.success, true]
        - eq: [content.msg, "user created successfully."]
```
