### ISSUE TITLE
testcase层hook机制无法使用

### ISSUE THREAD

**Issue by whitexie** [httprunner/httprunner#498]
## 问题描述

在config下添加了teardown_hooks，运行后未调用teardown_hooks下的set_config_parser方法。
日志最后有打印 ${set_config_parser(orderId, $orderId)}

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [macos,]
 - Python 版本 [3.6.3]
 - HttpRunner 版本 [2.0.1]

## 堆栈信息

![image](https://user-images.githubusercontent.com/30469146/51450920-bbbedf80-1d6d-11e9-94e9-d38123ab0091.png)

请提供出现 bug 时的详细堆栈内容。

## 项目文件结构

```
tests
│
├── testcases
    └── create_order_by_scan_take.yml

```

## 项目文件内容（非必须）
```
- config:
    name: 登陆->创建扫易得订单->支付订单
    id: userlogin
    base_url: ${get_url()}
    teardown_hooks:
        - ${set_config_parser(orderId, $orderId)}
```
如果可能，提供项目测试用例文件原始内容可加快 bug 定位和修复速度。

提示：请注意在去除项目敏感信息（IP、账号密码、密钥等）后再进行上传。
