### ISSUE TITLE
teststep中定义的 variables无效

### ISSUE THREAD

**Issue by AllenGuo-1** [HttpRunner/HttpRunner#500]
## 问题描述

定义了登陆后台和App的接口，分别需要两个appKey，case中调用是分别命名为appKey 和appkey2，在登陆后台的teststep中定义 appKey: $appKey2，执行失败，查看报告appKey使用的是 appKey而不是 appKey2
![Uploading image.png…]()

## 版本信息

请提供如下版本信息：

 - 操作系统类型: Mac OS
 - Python 版本 3.6.0
 - HttpRunner 版本 2.0.2

**Comment by debugtalk** [comment]
@AllenGuo-1 问题的原因在于 ，在 parse 环节，config 中的变量会完成运算，并且对 test 中的变量进行覆盖。

避免的方式：采用不同的变量名。


```yaml
- config:
    name: debug_case
    base_url: ${get_base_url()}
    variables:
        - appKey: ${get_appKey()}
        - appKey2: ${get_console_appKey()}
- test:
    name: 获取账号Apptoken
    variables:
        - device: xxxx
        - idfa: xxxx
        - timestamp: ${get_currentTimestamp()}
    api: auth($appKey,$device,$idfa,$timestamp)
    extract:
        - token: content.token

- test:
    name: 登录App账号
    variables:
        - account: "xxxxxx"
        - pwd: xxxxxx
    api: login($appKey,$token,$account,$pwd)
    extract:
        - uid: content.uid
        - trackinfo: content.userData.trackinfo

- test:
    name: 获取登录console需要的token
    variables:
        - device: "WEB_CONSOLE_SERVICE_RUN"
        - timestamp: ${get_currentTimestamp()}
    api: console_auth($appKey2,$device,$timestamp)
    extract:
         - token2: content.token

- test:
    name: 登录console
    variables:
        - account: "xxxxxx"
        - pwd: xxxxxx
        - token: $token2
    api: console_login($appKey2,$token,$account,$pwd)
    extract:
        - uid2: content.uid
```
