### ISSUE TITLE
测试用例中test部分定义的变量会被config中定义的全局变量覆盖

### ISSUE THREAD

**Issue by lunaragon** [HttpRunner/HttpRunner#524]
## 问题描述
在测试用例的 xxx.test.yaml 文件中；
若在 `config` 和 `test` 中均定义了同一变量
则在引用该变量时, 引用的值为config中定义的全局变量，与文档描述相反。

## 版本信息
 - 操作系统类型: macos
 - Python 版本 3.7
 - HttpRunner 版本 2.0.3

## 堆栈信息
未出错， 但是引用的变量值与预期不符合

## 项目文件结构

请提供测试用例的文件组织结构。比较好的方式是在项目根目录中执行`tree -a`命令。

## 项目文件内容（非必须）

```yaml
- config:
    name: 接口字段检测
    base_url: http://xxx.com
    variables:
        key_list: []
        use_default_flag: True

- test:
    name: 通知中心 - 资源更新检测 - 游戏键盘
    variables:
        key_list: ["wanted_field"]
    request:
        url: /api/field/check
        method: POST
        headers:
            cache-control: "no-cache"
        params:
            time: '19-02-25'
        data: 
            noti: ${make_noti_post_data($key_list, $use_default_flag)}
    teardown_hooks:
        - ${convert_response_to_json($response)}
    validate:
        - eq: [status_code, 200]
        - contains: [content, "wanted_field"]
```

`make_noti_post_data `定义在`debugtalk.py`文件中
```python
def make_noti_post_data(key_list, use_default_flag = True):
    print(key_list)
    noti = {}
    if use_default_flag:
        for key, value in NOTI_DEFAULT_OPTION.items():
            noti[key] = value
    for key_name in key_list:
        noti[key_name] = {"message_version": 0}
    return json.dumps(noti)
```

```bash
hrun testcases/my-case.yaml
```
log显示`key_list`为`config`中的空数组, 而不是`test`中定义的数组
其次，将config中定义的`key_list`去除即可解决改问题；

即变量的覆盖与文档中描述的正好相反
