### ISSUE TITLE
case执行失败后，执行不到teardown

### ISSUE THREAD

**Issue by testwangchao** [HttpRunner/HttpRunner#53]
单条case fail后，不会去执行teardown

**Comment by debugtalk** [comment]
@testwangchao 可否将你的YAML用例贴一下？

**Comment by testwangchao** [comment]
```
- test:
    name: search partner
    request:
        url: /admin/cp?id=$id&page=1&size=30&tableId=table
        method: GET
    teardown:
        - ${delete_data()}
    validate:
        - {"check": "content.data_type", "comparator": "eq", "expected": false}
```
delete_data()是删除从接口添加的数据的函数，在debugtalk里面放着，但是这条case 执行失败后，这个函数不会执行，pass的时候是可以的。
