### ISSUE TITLE
请问如何全局配置skipIf

### ISSUE THREAD

**Issue by caelansar** [HttpRunner/HttpRunner#592]
## 问题描述

如何在全局配置skip，即如何按照条件跳过一整个测试用例？

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [ macos ]
 - Python 版本 [3.7]
 - HttpRunner 版本 [2.1.2]

## 项目文件内容（非必须）

```yml
-   config:
        name: 接口测试
        skipIf: ${login_required()}
        base_url: http://xxx.com
        variables: {}
```
这样写无效，是否config不支持该配置项？

## 运行命令 && 堆栈信息
