### ISSUE TITLE
带中文参数请求会转为unicode，并且2.1.2无法通过data关键字解决

### ISSUE THREAD

**Issue by lichengxun** [httprunner/httprunner#614]
## 问题描述

遇到了 https://github.com/HttpRunner/HttpRunner/issues/395#issue-363556841 的问题，尝试使用data关键字解决时报错，提示编码问题

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [Windows]
 - Python 版本 [3.7]
 - HttpRunner 版本 [2.1.2]

## 项目文件内容（非必须）
```
name: 登录
base_url: ${ENV(base_url)}
variables:
    username: 用户名
    password: 密码

request:
    method: POST
    url: /v1/systemUser/login
    headers:
        Content-Type: text/plain
    data: '{"username": "$username","password": "$password"}'
    # json:
    #     username: $username
    #     password: $password

validate:
    - eq:
          - status_code
          - 200
```

## 运行命令 && 堆栈信息
Traceback (most recent call last):
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 14-16: Body ('用户名') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.
