### ISSUE TITLE
Question(Or Feature Request): 如何在json中模拟不存在字段？

### ISSUE THREAD

**Issue by EltonZhong** [HttpRunner/HttpRunner#620]
比如以下情况：
在一个api中 定义如下：
```yaml
- json:
    name: $name
    password: $name
```
当name  传入null的时候json为
```js
{
    "name": null, "password": ""
}
```

， 但是我希望可以在testcase中模拟这种情况：
```js
{
    "password": ""
}
```
即不存在name这个字段。（不改变api的情况下）

有没有合适的方式做这样的事情呢？在json body字段多的时候， 这个还是蛮重要的。
