### ISSUE TITLE
TestCase:  AttributeError: 'str' object has no attribute 'popitem'

### ISSUE THREAD

**Issue by pierre03** [HttpRunner/httprunner#649]
## Describe the bug
Hello, i got an exception when i create the testcase for the API.
It works if i test directly the api file by adding the config in the api file, but if i use the testcase to call the external api file, i got the error. i tried to call the other api files, but always the same error.
Can you tell me how to solve this problem, please?

```
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as t
he default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  yaml_content = yaml.load(stream)
ERROR    !!!!!!!!!! exception stage: load tests !!!!!!!!!!
**AttributeError: 'str' object has no attribute 'popitem'**
```

## Versions

Please complete the following information:

 - OS: windows
 - Python 3.6
 - HttpRunner [e.g. 1.5.11]

## Traceback

Traceback when bug occurs.

## Project structure

File structure of your project. A good way is to run `tree -a` command.

## Project files (If possible)

searchTestCase:

```
- config:
    name: searchApps
    base_url: http://localhost:8080
    variables:
        expected_status_code: 200
- test:
    name: search.
    testcase: api/local/searchApps.yaml
```

Api file searchApps.yaml:
```
name: searchApps
variables:
    expected_status_code: 200
request:
    headers:
        Content-Type: application/json
        User-Agent: Apache-HttpClient/4.1.1 (java 1.5)
    json:
        birthDate: '1900-03-05'
        firstName: ''
        size: '100'
        startIndex: '0'
    method: POST
    url: /Gui/searchApps
validate:
  - eq:
    - status_code
    - $expected_status_code
  - eq:
    - headers.Content-Type
    - application/json
  - eq:
    - content.totalSize
    - 615
  - eq:
    - content.status
    - '0'
  - eq:
    - content.errorMessage
    - null
```
