### ISSUE TITLE
如何断言返回值是html的内容？

### ISSUE THREAD

**Issue by testerwang11** [httprunner/httprunner#651]
## 问题描述

想使用httprunner做线上巡检，部分项目前后端没分离。现在登录能成功。返回的是html页面。如何写断言，检查下title？

**Comment by bruceqiao** [comment]
可以在 debugtalk 里自定义函数呀，比如简单的如下：
```python
def text_contains_sub(text, sub):
    result = text.find(sub)
    assert result != -1

```

然后在你的 api 里 validate 一下咯？

```yaml
validate:
  - eq:
      - status_code
      - 200
  - text_contains_sub:
      - text
      - "登录成功的某些关键字"
```
