### ISSUE TITLE
validate里有变量时，生成的report里expect内容是LazyString($expect_msg)

### ISSUE THREAD

**Issue by juan37** [httprunner/httprunner#693]
## 问题描述

testcase里的validate写的expect内容是用$变量参数传入的方式时，执行完用例后，report里的expect内容是LazyString($expect_msg)，无法看到真实的值

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [e.g. macos, Linux, Windows]
 - Python 版本 [e.g. 3.6]
 - HttpRunner 版本 [e.g. 2.2.5]

## 项目文件内容（非必须）

```
- config:
    name: XXXX
- test:
    name: $casename
    api: xxx/xxx/login.yaml
    setup_hooks:
        - ${add_signature($request)}
    validate:
        - eq: ['status_code',200]
        - eq: [content.errcode,'${to_int($expect_errcode)}']
        - eq: [content.msg,$expect_msg]
```

## 执行结果
见附件
![1](https://user-images.githubusercontent.com/17078188/64318712-4565a980-cfed-11e9-920b-f88223416ab9.png)
