### ISSUE TITLE
请问如何设置全局的 `response.encoding='utf-8'`

### ISSUE THREAD

**Issue by yexuesong** [httprunner/httprunner#748]
## 问题描述

请问如何设置全局的 `response.encoding='utf-8'`

目前报告中 `response.text` 内容是乱码的

**Comment by hazer491** [comment]
加hook函数？

**Comment by yexuesong** [comment]
@hazer491 
他这个hook 获取的 response 只是一个参数，没有 `response.encoding` 这个函数呀

**Comment by hazer491** [comment]
@yexuesong 
你可以用hook函数给response绑定参数的，例如：
def teardown_hook_set_encoding(response,attr):
    response.encoding = attr

**Comment by yexuesong** [comment]
试过，没能成功设置上编码。

```yml
    teardown_hooks:
        - ${teardown_hook_set_encoding($response, utf-8)}
    extract:
        title: '<title>(.*)</title>'
    validate:
    -   eq:
        - status_code
        - 200
    -   eq:
        - headers.Content-Type
        - text/html
    -   eq:
        - $title
        - 控制板
```

```python
def teardown_hook_set_encoding(response, attr):
    response.encoding = attr
    return response
```
> 生成的 TestReport 

![data](https://user-images.githubusercontent.com/25861775/68443781-f23bed00-020f-11ea-9400-9802fcc2a2d2.png)

**Comment by hazer491** [comment]
tear_down hook好像真的只能对已经返回的response进行处理，加属性并不能让httprunner按我们加的属性来重新获得response. 这个还真的是个问题

**Comment by debugtalk** [comment]
@yexuesong 你试下这样可以么？

```python
def teardown_hook_set_encoding(response, attr):
    response. resp_obj.encoding = attr
    return response
```

**Comment by debugtalk** [comment]
考虑在 config 和 teststep 中新增支持 `response_encodiing` 字段，用于设置 response.encoding。

```yaml
config:
    name: "setup and reset all."
    id: setup_and_reset
    variables:
        user_agent: 'iOS/10.3'
        device_sn: "TESTCASE_SETUP_XXX"
        os_platform: 'ios'
        app_version: '2.8.6'
    base_url: "http://127.0.0.1:5000"
    response_encodiing: utf-8
    verify: False
    export:
        - session_token

teststeps:
-
    name: get token (setup)
    response_encodiing: utf-8
    api: api/get_token.yml
    variables:
        user_agent: 'iOS/10.3'
        device_sn: $device_sn
        os_platform: 'ios'
        app_version: '2.8.6'
    extract:
        - session_token: content.token
    validate:
        - eq: ["status_code", 200]
        - len_eq: ["content.token", 16]
-
    name: reset all users
    api: api/reset_all.yml
    variables:
        token: $session_token
```
