### ISSUE TITLE
如何正确的传递dict参数到请求中

### ISSUE THREAD

**Issue by Kewings** [httprunner/httprunner#767]
## 问题描述

需要在get的API中传递value = {dict} 的参数
一开始用：
```
name: set ip_disnation
variables:
  ip_disnation:
    "IPv4": "192.168.1.201"
    "Port": 2368
    "GpsPort": 10110
request:
  url: "/test.cgi"
  method: GET
  params:
    action: set
    object: xxxx
    key: ip_disnation
    value: "$ip_disnation"
validate:
    - eq: ["content.Head.ErrorCode", '0']
    - eq: ["content.Head.Message","Success"]
```

传递出去的参数会是value =IPv4&value=port&value=gpsport

后来修改成：

```
name: set ip_disnation
variables:
  ip_disnation:
    - [{"IPv4":"255.255.255.255","Port":2368,"GpsPort":10110}]
request:
  url: "/pandar.cgi"
  method: GET
  params:
    action: set
    object: lidar
    key: ip_disnation
    value: "$ip_disnation"
validate:
    - eq: ["content.Head.ErrorCode", '0']
    - eq: ["content.Head.Message","Success"]
```

传递出去的value=%7B%27IPv4%27%3A+%27255.255.255.255%27%2C+%27Port%27%3A+2368%2C+%27GpsPort%27%3A+10110%7D

如何解决？求支持

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [Windows]
 - Python 版本 [3.7.3]
 - HttpRunner 版本 [2.2.5]
