### ISSUE TITLE
extract提取值报错时可以给变量设置默认值吗

### ISSUE THREAD

**Issue by maxiaoqian** [httprunner/httprunner#792]
## 场景描述：例如2个接口有依赖
1. 登录接口，登录成功后返回token
2. 获取用户信息，使用登录后返回的token

```
-test:
    name: 登录账号
    request:
       method: POST
       url: /api/login
       json:
           username: xxx
           password: xxx
    validate:
         - eq: [status_code, 200]
   extract:
        - login_token: content.token

- test:
    name: 获取用户信息
    skipIf()   # 如果获取不到token就跳过该条用例
    request:
        method: GET
        url: info/token=$login_token
    validate:
       - eq: [status_code, 200]
```

## 问题：
- 问题：调用获取用户接口时，无法根据token是否正常获取到去判断是否skip获取用户信息接口。因为如果登录接口报错是不会返回token的，此时extract就会报错。
- 提问：对于上诉这种情况httprunner怎么处理？？
- 其他：如果是对于pytest的话，基本就是获取token失败的时候默认返回空字符串，然后执行获取用户信息时根据token是否为空就行过滤
