### ISSUE TITLE
调用企业微信公众号接口发送消息时，消息内容有中文，发送后，微信端展示的是\u4f60\u59b9等unicode码

### ISSUE THREAD

**Issue by wixed** [HttpRunner/HttpRunner#83]
#### 以下为yml脚本
```
- test:
    name: 发送消息
    request:
      url: https://qyapi.weixin.qq.com/cgi-bin/message/send?access_token=$access_token
      method: POST
      json:
          text:
            content: 中文测试
          toparty: 1
          agentid: 1
          msgtype: text

    extract:
        - Tags : content.errmsg
    validate:
        - {"check": "status_code", "comparator": "eq", "expect": 200}
        - {"check": "content.errmsg", "comparator": "eq", "expect": ok}
```
python 2.7
经过测试发现，处理data时要这样操作
```
header_dict = json.dumps(header_dict, ensure_ascii=False)
res = urllib2.urlopen(url,header_dict)
```
微信端才能展示中文。
所以想问一下，在httprunner如何解决这个问题
