### ISSUE TITLE
Python3: Error in atexit._run_exitfuncs

### ISSUE THREAD

**Issue by maxiaoqian** [httprunner/httprunner#844]
## 问题描述

运行httprunner生成报告后有报错

## 版本信息

请提供如下版本信息：

 - 操作系统类型: Windows
 - Python 版本： 3.7.0
 - HttpRunner 版本 2.2.5

## 项目文件内容（非必须）
```
- config:
    name: 百度

- test:
    name: 访问百度
    request:
        method: GET
        url: https://www.baidu.com
   validate:
        - eq: [status_code, 200]
```

## 运行命令 && 堆栈信息

![image](https://user-images.githubusercontent.com/12823798/71882071-a6a1b300-316e-11ea-9ef2-138c7e654e49.png)

- 目前报错没啥影响，因为报告已经生成了，但是以前都没报错过。现在这报错很奇怪
