### ISSUE TITLE
hrun命令出现utf-8报错

### ISSUE THREAD

**Issue by MaChangLei** [httprunner/httprunner#909]
hrun执行出现报错：

```text
$ hrun online.yml
2020-05-26 08:54:04.188 | INFO     | httprunner.ext.make:make_testcase:80 - start to make testcase: online.yml
2020-05-26 08:54:04.194 | INFO     | httprunner.ext.make:make_testcase:108 - generated testcase: online_test.py
2020-05-26 08:54:04.194 | INFO     | httprunner.ext.make:format_pytest_with_black:63 - format pytest cases with black ...
error: cannot format online_test.py: 'utf-8' codec can't decode byte 0xb3 in position 1872: invalid start byte
Oh no! \U0001f4a5 \U0001f494 \U0001f4a5
1 file failed to reformat.
============================= test session starts =============================
platform win32 -- Python 3.8.3, pytest-5.4.2, py-1.8.1, pluggy-0.13.1
rootdir: E:\Project\httprunner
plugins: allure-pytest-2.8.15
collected 0 items / 1 error

=================================== ERRORS ====================================
_______________________ ERROR collecting online_test.py _______________________
d:\python38\lib\site-packages\_pytest\python.py:511: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
d:\python38\lib\site-packages\py\_path\local.py:701: in pyimport
    __import__(modname)
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:975: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:671: in _load_unlocked
    ???
d:\python38\lib\site-packages\_pytest\assertion\rewrite.py:143: in exec_module
    source_stat, co = _rewrite_test(fn, self.config)
d:\python38\lib\site-packages\_pytest\assertion\rewrite.py:328: in _rewrite_test
    tree = ast.parse(source, filename=fn)
d:\python38\lib\ast.py:47: in parse
    return compile(source, filename, mode, flags,
E     File "E:\Project\httprunner\online_test.py", line 11
E   SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xb3 in position 0: invalid start byte
=========================== short test summary info ===========================
ERROR online_test.py
!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
============================== 1 error in 0.45s ===============================
```

附上源yml文件：

```yaml
config:
    name: testcase description
    variables: {}
    verify: false
teststeps:
-   name: /clean/cmd/send
    request:
        cookies:
            q: u=zn.punatyrv&n=%Q4%R7%PQ%RQ%O4%S2%O6%O9%O6%O9&le=nTSwn2IlrKIhWGDjZGV2YzAioD==&m=ZGZjWGWOWGWOWGWOWGWOWGWOZmNk&qid=1331141188&im=1_t016180b3619fa6823b&src=mpc_smarthome_ios&t=1
            qid: '1331141188'
            sid: d32cf5481812b49af209276cd102ca39
            t: s=2294a7500a20330930e6702809bc08dc&t=1590473655&lm=&lf=2&sk=08d4754c319995f7929ab76c51a883ba&mt=1590473655&rc=&v=2.0&a=1
        data:
            countryId: US
            data: ''
            devType: '3'
            from: mpc_ios
            infoType: '20001'
            lang: zh_CN
            sn: 369CN500101000047
            taskid: A7D32A14-E1CB-465C-88B9-7D5C68272281
        headers:
            Accept: '*/*'
            Accept-Encoding: gzip, deflate, br
            Accept-Language: zh-Hans-US;q=1, en-US;q=0.9
            Connection: keep-alive
            Content-Length: '132'
            Content-Type: application/x-www-form-urlencoded
            Cookie: q=u=zn.punatyrv&n=%Q4%R7%PQ%RQ%O4%S2%O6%O9%O6%O9&le=nTSwn2IlrKIhWGDjZGV2YzAioD==&m=ZGZjWGWOWGWOWGWOWGWOWGWOZmNk&qid=1331141188&im=1_t016180b3619fa6823b&src=mpc_smarthome_ios&t=1;t=s=2294a7500a20330930e6702809bc08dc&t=1590473655&lm=&lf=2&sk=08d4754c319995f7929ab76c51a883ba&mt=1590473655&rc=&v=2.0&a=1;qid=1331141188;sid=d32cf5481812b49af209276cd102ca39
            Host: q.smart.360.cn
            User-Agent: QihooSuperApp_NoPods/7.0.0 (iPad; iOS 13.2.3; Scale/2.00)
        method: POST
        url: https://q.smart.360.cn/clean/cmd/send
    validate:
    -   eq:
        - status_code
        - 200
    -   eq:
        - headers.Content-Type
        - application/json; charset=utf-8
    -   eq:
        - body.errno
        - 0
    -   eq:
        - body.errmsg
        - 成功
```
