### ISSUE TITLE
在testcase中引用testcase，外层的validate在生成.py测试用例时没有生效

### ISSUE THREAD

**Issue by ArthurSmoke** [httprunner/httprunner#934]
## 问题描述

在testcase中引用testcase，外层的断言在生成.py测试用例时没有生效

## 版本信息

请提供如下版本信息：

 - 操作系统类型: macos
 - Python 版本 3.7.7
 - HttpRunner 版本 3.0.12
 - **设备 ID**: 26824500691243

获取方式：

在 Python 交互式 shell 中输入如下命令进行获取：

```bash
>>> import uuid; print(uuid.getnode())
190070690681122
```

## 项目文件内容（非必须）
api/api_A.yml
```yml
config:
    name: apiA
teststeps:
-
    name: stepA
    request:
        url: /XX
        method: POST
    validate:
        - eq: ["status_code", 200]
```

testcase
```yml
config:
    name: testA
testcases:
-
    name: testA
    testcase: api/api_A.yml
    validate:
        - type_match: [body.data.origin.width, int]

```
生成的api_A_test.py中只有status_code的断言，没有type_match的类型检查断言
