### ISSUE TITLE
在teststep中引用testcase，外层的validate在生成.py测试用例时没有生效，3.0.5可以，3.0.12不行

### ISSUE THREAD

**Issue by ArthurSmoke** [httprunner/httprunner#936]
## 问题描述

在teststep中引用testcase，外层的validate在生成.py测试用例时没有生效，
3.0.5可以，3.0.12不行

## 版本信息

请提供如下版本信息：

 - 操作系统类型: macos
 - Python 版本 3.7.7
 - HttpRunner 版本 3.0.12
 - **设备 ID**: 26824500691243

## 项目文件内容（非必须）

api/api_A.yml
```yml
config:
    name: apiA
teststeps:
-
    name: stepA
    request:
        url: /XX
        method: POST
    validate:
        - eq: ["status_code", 200]
```

testcase
```yml
config:
    name: testA
teststeps:
-
    name: testA
    testcase: api/api_A.yml
    validate:
        - type_match: [body.data.origin.width, int]
```

## 运行命令 && 堆栈信息

```bash
==================================== ERRORS ====================================
_____________ ERROR collecting testcases/imageServiceTest_test.py ______________
testcases/imageServiceTest_test.py:14: in <module>
    class TestCaseImageservicetest(HttpRunner):
testcases/imageServiceTest_test.py:39: in TestCaseImageservicetest
    .call(Segmentmix)
E   AttributeError: 'StepRefCase' object has no attribute 'validate'
=========================== short test summary info ============================
ERROR testcases/imageServiceTest_test.py - AttributeError: 'StepRefCase' obje...
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.48s ===============================
```
