### ISSUE TITLE
suite文件夹下的yml文件如何描述

### ISSUE THREAD

**Issue by happyMeiyo** [HttpRunner/HttpRunner#95]
在`ttpRunner项目的examples/HelloWorld目录中"，然而似乎并没有提交到github上。

suite下的文件如何描述，一直没看懂呢，请解答

**源代码看了两三次，都不明白suite下的yml文件该怎么描述** 

**请解答，万分谢谢！！**

**Comment by masen931005** [comment]
-config
 def:function1()
我看好像是这样的，一个yml文件调一个api，这样多个yml放在一个文件夹下就组合一个组件。

**Comment by happyMeiyo** [comment]
@masen931005 你运行成功了嘛？suite文件中，如何调用API呢？

**Comment by wushenghang** [comment]
```
- config:
    def: suite_codeLogin($timestamp,$phone)
- test:
    name: 获取验证码
    api: api_sms_loginCode_POST($timestamp,$phone)
- test:
    name: 验证码登录
    variables:
        sms_code: ${getSmsCode()}
    api: api_user_smsLogin_POST($sms_code,$timestamp,$phone)
```
