### ISSUE TITLE
3.X版本的teststeps.variables和config.parameters的区别能否说明下？

### ISSUE THREAD

**Issue by WangDW68** [httprunner/httprunner#964]
## 问题描述
3.X版本的teststeps.variables和config.parameters的区别能否说明下？

请对遇到的 bug 进行简要描述。
升级到3.1.3之后、使用debugtalk函数获取参数的方式不在支持数组了吗？参数信息应该放在teststeps.variables中还是放在config.parameters中呢？目前我将debugtalk函数放在teststeps.variables中且将函数返回值设置为对象是可以正常执行。

## 版本信息
请提供如下版本信息：
 - 操作系统类型: macos
 - Python 版本  : 3.7.7
 - HttpRunner 版本 [e.g. 2.1.2]
 - **设备 ID**: [e.g. 190070690681122]

```
期望：能否像2.X的版本、debugtalk函数支持数组返回值。用例执行次数能够根据参数列表进行笛卡尔积组合。覆盖所有参数组合情况

**Comment by WandyYing** [comment]
@zaizaiDaxia 你好，config.parameters并未改变原来teststeps.variables的运作方式。 针对你的笛卡尔积需求，请参考例子https://github.com/httprunner/httprunner/blob/master/examples/postman_echo/request_methods/request_with_parameters.yml

**Comment by larajiao** [comment]
如果参数是dict，里面有，会被截断

**Comment by WandyYing** [comment]
@larajiao 你好，我个人的理解是，csv不要去直接存放dict，xml等格式。而是利用csv 配合 yaml或者函数 去构建所需要的dict。
例如：
1. csv配合函数的话，函数提供dict或者xml的模板，csv读入的数据填充模板，生成测试所需要的List[dict]。
2. csv 配合yaml实现dict，将csv中的变动的部分放入csv，例如下面的例子。$account 即可使用 字典{"username“: $user....}
```
config:
    parameters:
        user-pass: ${parameterize(request_methods/account.csv)}

teststeps:
    variables:
        account:
            username: $user
            password: $pass
            auth: True
            other_arr: other
.....               

```
