### ISSUE TITLE
3.1.3 版本request中的json无法支持自$BodyJson格式的json输入

### ISSUE THREAD

**Issue by WandyYing** [httprunner/httprunner#971]
## 问题描述

代码片段如下:
```
 request:
        method: POST
        url: /post
        headers:
            User-Agent: HttpRunner/${get_httprunner_version()}
            Content-Type: "text/plain"
        # data: "This is expected to be sent back as part of response body: $foo1-$foo2-$foo3."
        json: $bodyjson
```
 由于module限制， 无法支持 json: $bodyjson 这种方式的json输入。
